apiVersion: v2
name: onetimesecret
version: 0.12.2
description: A Helm chart for One-Time Secret server
type: application
keywords:
  - onetimesecret
  - ots
  - onetimepassword
  - otp
home: https://github.com/indiegogo/onetimesecret
sources:
  - https://github.com/indiegogo/onetimesecret
  - https://github.com/onetimesecret/onetimesecret
dependencies:
  - name: common
    version: 1.x.x
    repository: https://charts.bitnami.com/bitnami
  - name: redis
    version: "0.4.6"
    repository: https://groundhog2k.github.io/helm-charts/
    condition: redis.chartEnabled
maintainers:
  - name: DevOps
    email: devops@indiegogo.com
icon: https://github.com/indiegogo/onetimesecret/blob/main/public/web/img/logo-57.png
appVersion: "0.11-rc.1"
